version: "3.9"

services:
  db:
    container_name: allure_db
    image: postgres:latest
    ports:
      - ${DB_PORT:-5432}:5433
    volumes:
      - db_vol:/var/lib/postgresql/data1
    environment:
      POSTGRES_PASSWORD: ${DB_PASS:-Admin@123}
      POSTGRES_DB: ${DB_NAME:-allure}
      POSTGRES_USER: ${DB_USER:-postgres}
      TZ: ${TZ:-"Asia/Ho_Chi_Minh"}
    networks:
      - allure_network

  redis:
    image: redis:latest
    container_name: redis_queue
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_vol:/data
    command: redis-server --appendonly no --replica-read-only no
    environment:
      TZ: ${TZ:-"Asia/Ho_Chi_Minh"}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - allure_network

  adminer:
    image: adminer:4.8.1
    ports:
      - ${ADMINER_PORT:-8080}:8080
    environment:
      TZ: ${TZ:-"Asia/Ho_Chi_Minh"}
    depends_on:
      - db
    networks:
      - allure_network

networks:
  allure_network:
    name: allure_network
    driver: bridge
    external: true

volumes:
  db_vol:
    driver: local
  redis_vol:
    driver: local
