version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: minhpham11311/allure-app:latest

  # You can add other services here if you want to build and push them too
