version: "3.9"

services:
  app:
    image: minhpham11311/allure-app:latest
    container_name: allure_app
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
      - TZ=${TZ:-"Asia/Ho_Chi_Minh"}
      # Database
      - DB_HOST=allure_db
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASS=${DB_PASS:-Admin@123}
      - DB_NAME=${DB_NAME:-allure}
      # Redis
      - REDIS_HOST=redis_queue
      - REDIS_PORT=${REDIS_PORT:-6379}
      # JWT
      - SECRET_KEY_FOR_ACCESS_TOKEN=${SECRET_KEY_FOR_ACCESS_TOKEN}
      - SECRET_KEY_FOR_REFRESH_TOKEN=${SECRET_KEY_FOR_REFRESH_TOKEN}
      # Google Login
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
      # Email
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - FROM_EMAIL=${FROM_EMAIL}
      # Firebase
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
      - FIREBASE_APP_ID=${FIREBASE_APP_ID}
      - FIREBASE_MEASUREMENT_ID=${FIREBASE_MEASUREMENT_ID}
      # Agora
      - AGORA_APP_ID=${AGORA_APP_ID}
      - AGORA_APP_CERTIFICATE=${AGORA_APP_CERTIFICATE}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - allure_network

networks:
  allure_network:
    name: allure_network
    driver: bridge
    external: true
