import express from "express";
import accountRouter from "./account.route";
import authRoute from "./auth.route";
import brandRoute from "./brand.route";
import addressRouter from "./address.route";
import categoryRouter from "./category.router";
import productClassificationRouter from "./productClassification.route";
import productRouter from "./product.route";
import roleRouter from "./role.route";
import preOrderProductRouter from "./preOrderProduct.route";
import fileRouter from "./file.route";
import productDiscountRouter from "./productDiscount.route";
import cartItemRouter from "./cartItem.route";
import orderRouter from "./order.route";
import voucherRouter from "./voucher.route";
import groupProductRouter from "./groupProduct.route";
import groupBuyingRouter from "./groupBuying.route";
import consultantServiceRouter from "./consultantService.route";
import paymentRouter from "./payment.route";
import systemServiceRouter from "./systemService.route";
import walletRouter from "./wallet.route";
import slotRouter from "./slot.route";
import bookingRoute from "./booking.route";
import consultationCriteriaRoute from "./consultationCriteria.route";
import serviceBookingFormRouter from "./serviceBookingForm.route";
import feedbackRouter from "./feedback.route";
import consultationCriteriaSectionRouter from "./consultationCriteriaSection.route";
import questionRouter from "./question.route";
import masterConfigRouter from "./masterConfig.route";
import transactionRouter from "./transaction.route";
import reportRouter from "./report.route";
import livestreamRouter from "./livestream.route";

const router = express.Router();
router.use("/accounts", accountRouter);
router.use("/auth", authRoute);
router.use("/role", roleRouter);
router.use("/brands", brandRoute);
router.use("/address", addressRouter);
router.use("/category", categoryRouter);
router.use("/product-classification", productClassificationRouter);
router.use("/pre-order-product", preOrderProductRouter);
router.use("/product-discount", productDiscountRouter);
router.use("/products", productRouter);
router.use("/cart", cartItemRouter);
router.use("/files", fileRouter);
router.use("/orders", orderRouter);
router.use("/vouchers", voucherRouter);
router.use("/group-products", groupProductRouter);
router.use("/group-buyings", groupBuyingRouter);
router.use("/consultant-services", consultantServiceRouter);
router.use("/system-services", systemServiceRouter);
router.use("/payments", paymentRouter);
router.use("/wallets", walletRouter);
router.use("/slots", slotRouter);
router.use("/bookings", bookingRoute);
router.use("/service-booking-forms", serviceBookingFormRouter);
router.use("/questions", questionRouter);
router.use("/consultation-criteria", consultationCriteriaRoute);
router.use(
  "/consultation-criteria-sections",
  consultationCriteriaSectionRouter
);
router.use("/feedbacks", feedbackRouter);
router.use("/master-config", masterConfigRouter);
router.use("/transactions", transactionRouter);
router.use("/reports", reportRouter);
router.use("/livestreams", livestreamRouter);
export default router;
